
import { MazeJson, MazeLayout } from "./maze_types";
import { parseMazeJson } from "./maze_validate";

export interface LevelDef {
    id: number;
    title: string;
    lesson: string;
    badge: string;
    hint: string;
    maze: MazeJson;
}

const LEGEND = {
    "#": "wall",
    ".": "floor",
    S: "start",
    G: "goal",
} as const;

export const LEVELS: LevelDef[] = [
    {
        id: 1,
        title: "1. The Hallway",
        lesson: "Rewards",
        badge: "The Reward Wrangler",
        hint: "A straight path. The agent learns that moving towards the Goal (G) gives the best reward.",
        maze: {
            name: "The Hallway",
            size: 9,
            legend: LEGEND,
            grid: [
                "#########",
                "#########",
                "##S.....G##",
                "#########",
                "#########",
                "#########",
                "#########",
                "#########",
                "#########",
            ],
        },
    },
    {
        id: 2,
        title: "2. The Choice",
        lesson: "Exploration",
        badge: "Explorer of Choices",
        hint: "Two paths to the goal. One is short, one is long. Can the agent find the fastest way?",
        maze: {
            name: "The Choice",
            size: 9,
            legend: LEGEND,
            grid: [
                "#########",
                "S.......#",
                "#######.#",
                "#######.#",
                "#######.#",
                "#######.#",
                "#######.#",
                "G.......#",
                "#########",
            ],
        },
    },
    {
        id: 3,
        title: "3. The Trap",
        lesson: "Negative Rewards",
        badge: "Trap Detector",
        hint: "A 'dead end' looks closer to the goal, but it's a trap! The agent must learn to back up.",
        maze: {
            name: "The Trap",
            size: 9,
            legend: LEGEND,
            grid: [
                "#########",
                "#S......#",
                "#######.#",
                "#G#####.#",
                "#.#####.#",
                "#.#####.#",
                "#.......#",
                "#########",
                "#########",
            ],
        },
    },
    {
        id: 4,
        title: "4. The Labyrinth",
        lesson: "Memory (Q-Table)",
        badge: "Memory Master",
        hint: "A classic maze. The agent needs a big memory (Q-Table) to solve this complex puzzle.",
        maze: {
            name: "The Labyrinth",
            size: 11,
            legend: LEGEND,
            grid: [
                "###########",
                "#S........#",
                "#.#######.#",
                "#.#.....#.#",
                "#.###.###.#",
                "#...#...#.#",
                "###.###.#.#",
                "#.......#.#",
                "#.#######.#",
                "#........G#",
                "###########",
            ],
        },
    },
    {
        id: 5,
        title: "5. The Race",
        lesson: "Efficiency",
        badge: "RL Hero Champion",
        hint: "Wide open space with obstacles. The challenge is to find the absolute shortest diagonal path.",
        maze: {
            name: "The Race",
            size: 11,
            legend: LEGEND,
            grid: [
                "###########",
                "#S........#",
                "#.#.###.#.#",
                "#.#.....#.#",
                "#...#.#...#",
                "###.#.#.###",
                "#...#.#...#",
                "#.#.....#.#",
                "#.#.###.#.#",
                "#........G#",
                "###########",
            ],
        },
    },
    {
        id: 6,
        title: "6. The Long Run",
        lesson: "Discount Factors",
        badge: "Future Visionary",
        hint: "A very long path with small rewards along the way. Will the agent focus on the big goal at the end?",
        maze: {
            name: "The Long Run",
            size: 13,
            legend: LEGEND,
            grid: [
                "#############",
                "#S..........#",
                "###########.#",
                "#..........##",
                "#.###########",
                "#..........##",
                "###########.#",
                "#..........##",
                "#.###########",
                "#..........##",
                "###########.#",
                "G...........#",
                "#############",
            ],
        },
    },
    {
        id: 7,
        title: "7. The Quick Study",
        lesson: "Learning Rate",
        badge: "Fast Learner",
        hint: "A maze that changes slightly (conceptually). How fast can the agent update its memory?",
        maze: {
            name: "The Quick Study",
            size: 9,
            legend: LEGEND,
            grid: [
                "#########",
                "#S#...#G#",
                "#.#.#.#.#",
                "#.#.#.#.#",
                "#...#...#",
                "###.###.#",
                "#.......#",
                "#.# #####",
                "###.#####",
            ],
        },
    },
    {
        id: 8,
        title: "8. Sparse Secrets",
        lesson: "Sparse Rewards",
        badge: "Persistence Pro",
        hint: "A large open room where the goal is hard to find. The agent gets NO rewards until it hits the goal.",
        maze: {
            name: "Sparse Secrets",
            size: 15,
            legend: LEGEND,
            grid: [
                "###############",
                "#S............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#.............#",
                "#............G#",
                "###############",
            ],
        },
    },
    {
        id: 9,
        title: "9. The General",
        lesson: "Generalization",
        badge: "Master Generalizer",
        hint: "Multiple similar rooms. Can the agent use knowledge from one room to solve the others?",
        maze: {
            name: "The General",
            size: 13,
            legend: LEGEND,
            grid: [
                "#############",
                "#S..#....#..#",
                "#...#....#..#",
                "##.###.####.#",
                "#..#....#...#",
                "#..#....#...#",
                "####.####.###",
                "#....#....#.#",
                "#....#....#.#",
                "##.####.###.#",
                "#..#....#..G#",
                "#..#....#...#",
                "#############",
            ],
        },
    },
    {
        id: 10,
        title: "10. The Ultimate Test",
        lesson: "Full Integration",
        badge: "RL Grandmaster",
        hint: "The final challenge. All concepts combined. Traps, long paths, and sparse rewards.",
        maze: {
            name: "The Ultimate Test",
            size: 17,
            legend: LEGEND,
            grid: [
                "#################",
                "#S..............#",
                "#.###############",
                "#.#.............#",
                "#.#.###########.#",
                "#.#.#.........#.#",
                "#.#.#.#######.#.#",
                "#.#.#.#.....#.#.#",
                "#.#.#.#.###.#.#.#",
                "#.#.#.#.#G#.#.#.#",
                "#.#.#.#.###.#.#.#",
                "#.#.#.#.....#.#.#",
                "#.#.#.#######.#.#",
                "#.#.#.........#.#",
                "#.#.###########.#",
                "#.#.............#",
                "#################",
            ],
        },
    },
];

export function loadLevel(id: number): MazeLayout {
    const def = LEVELS.find((l) => l.id === id);
    if (!def) throw new Error(`Level ${id} not found`);
    return parseMazeJson(def.maze);
}
